### PR TITLE
pagination bug fix, ui tweaks on next/prev page

### LINKED ISSUE #5: [Bug] - No upper limit on page number
Currently, there is a guard clause preventing the user from decrementing the page number lower than `1`.

https://github.com/TellemBigAlsentya/local-storage-favorites/blob/8d48115ede34b93bb94d3e0d2838186582c078a2/app.js#L35

Could we introduce a similar guard clause to prevent the user from incrementing the page number too high? 

🤔 **Note:** In the event of a new season of Rick & Morty, there may be more characters introduced to the API. We should attempt a solution that will be "future proof". In other words, we should not have to edit our front end every time the API content changes.

### PR DESCRIPTION
**Pull request by alexhoffman-dev**
Fixes: https://github.com/TellemBigAlsentya/local-storage-favorites/issues/5

buttons, styling tweaks

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -88,16 +92,16 @@ async function getData(queryParam, destination) {
...
         cardContainer.innerHTML = '';
     } else {
         favoriteBar.innerHTML = '';
     }
     const collection = destination === 'grid' ? characterGridData : favoriteCharactersData;
-    console.log(collection);
     collection.forEach((character) => {
         if(destination === 'grid') {
             renderCard(character);
+            disablePageButtons();
```
Comment (Luke9389) [inline app.js]: I don't think this is the correct place to be calling `disablePageButtons`.
Notice that this is inside of a `forEach` loop, so we are going to be calling this function for every single card.

File: app.js [hunk 2]
```diff
@@ -161,8 +165,21 @@ function toggleHeartDisplay(event) {
...
     return Boolean(favorites.split(',').find(elem => elem == id));
 }
+
+function paginationCheck(pageButton) {  
+    if(pageButton === 'next-page' && currentPageData.next) {
+        return true; 
+    } else if(pageButton === 'previous-page' && currentPageData.prev) {
+        return true;
+    } else {return false;}
+}
```
Comment (Luke9389) [inline app.js]:
```suggestion
function paginationCheck(pageButton) {  
    return pageButton === 'next-page' ? currentPageData.next : currentPageData.prev;
}
```

Comment (Luke9389) [reply app.js]: I've given a refactoring suggestion for this function above. I'll give some context here.

If you ever have code of the form 
```js
if (myCondition) {
    return true
} else {
    return false
}
```
that's the same as doing this
```js
return myCondition;
```
**_as long as `myCondition` is actually a boolean._** 

---

In my suggested version of this function, we actually end up returning the value of `currentPageData.next` and `currentPageData.prev`. If we wanted to only ever return a pure boolean we could do something like:

```js
function paginationCheck(pageButton) {
    const pageData = pageButton === 'next-page' ? currentPageData.next : currentPageData.prev;
    return Boolean(pageData)
}
```

But since we only ever call this function inside of an `if` condition, I think it's fine to return truthy values instead of booleans.

File: app.js [hunk 3]
```diff
@@ -161,8 +165,21 @@ function toggleHeartDisplay(event) {
...
+
+function disablePageButtons() {
+    nextPage.disabled = currentPageData.next ? false : true; 
+    prevPage.disabled = currentPageData.prev ? false : true; 
+}
```
Comment (Luke9389) [inline app.js]:
```suggestion
function disablePageButtons() {
    nextPage.disabled = !currentPageData.next;
    prevPage.disabled = !currentPageData.prev;
}
```

File: styles.css [hunk 4]
```diff
@@ -271,6 +271,16 @@ hr {
...
+button:disabled {
+    opacity: 20%;
+    fill: gray;
+}
+button:disabled:hover {
+    cursor: not-allowed!important;
+    opacity: 20%!important;
+    fill: gray!important;
+    border: solid 3px black!important;
+}
```
Comment (Luke9389) [inline styles.css]: Are the `!important` keywords necessary here? 

You could try switching the position of this css rule with `button:disabled` and see if you can take them out. 

If you need to leave them in, toss a space between the value and the `!important` keyword

Example
`cursor: not-allowed !important`

File: app.js [hunk 5]
```diff
@@ -29,12 +31,13 @@ async function load() {
...
-    if (currentPage < 1) { currentPage = 1; }
-    await getData(`?page=${currentPage}`, 'grid');
-    await showData('grid');
+    let targetID = event.target.id; 
+    if(paginationCheck(targetID)) {
+        currentPage = targetID === 'next-page' ? currentPage + 1 : currentPage - 1;
+        await getData(`?page=${currentPage}`, 'grid');
+        await showData('grid');
+    } 
+
```
Comment (Luke9389) [inline app.js]:
```suggestion
    let targetID = event.target.id; 
    if (!paginationCheck(targetID)) {
        return;
    }
    
    currentPage = targetID === 'next-page' ? currentPage + 1 : currentPage - 1;
    await getData(`?page=${currentPage}`, 'grid');
    await showData('grid');
```

It's better to have an early return than to wrap the contents of a function inside of a condition. 

One way you can keep an eye out for this is that the end of the code block after the `if` is also the end of your function. 

Example of what not to do:
```js
function something(event) {
    const myCondition = event.condition
    if (myCondition) {
        // All of the contents of the something function are in here
        code
        code
        code
    } // end of code block for if statement
} // end of code block
```

Example of what to do:
```js
function something(event) {
    const myCondition = event.condition
    if (!myCondition) {
        return; // early return 
    }
    
    // rest of the function
    code
    code
    code
}
```

File: index.html [hunk 6]
```diff
@@ -15,14 +15,15 @@ <h1> Rick and Morty Character Index </h1>
...
+            <div id="favorite-card-container"></div>
         </div>
         <hr style="border: dashed black 3px">
         <div id="filterAndCardContainer">
             <div id="filterBarContainer">
                 <label for="card-search"> Search: </label>
                 <input type="search" id="filter-search" placeholder="name"></input>
-                <div id="previous-page" class="changePage">Previous - Page</div>
-                <div id="next-page" class="changePage">Next - Page</div>
+                <button id="previous-page" class="changePage">Previous - Page</button>
```
Comment (Luke9389) [inline index.html]:
```suggestion
                <button disabled id="previous-page" class="changePage">Previous - Page</button>
```

You can do this instead of disabling it at the beginning of your JavaScript file.

**Review by Luke9389 — CHANGES_REQUESTED** [review]
Good start! Here are some suggestions. 

Btw every time i use the `Commit Suggestion` button in GH something breaks. I don't recommend it 😆

File: styles.css (hunk 4 above)
Comment (alexhoffman-dev) [reply styles.css]: I tried re-arranging these styles but since the next/previous page buttons have styling as well as styling on hover that are designated by their id's ie. `id=previous-page`, the scope overrules the `button:disabled` pseudo-class. 

I'll take a look and see if I can think of a smoother way to do that without the `!important` tag

Comment (Luke9389) [reply styles.css]: Word. Sounds good. It's not a huge deal, so don't spend too much time on it. Keeping them is fine.

File: app.js (hunk 1 above)
Comment (alexhoffman-dev) [reply app.js]: Totally agree -- I do think that this function should be called within `showData`, so I've moved it to the end of the function after the forEach loop concludes.

File: app.js (hunk 2 above)
Comment (alexhoffman-dev) [reply app.js]: That makes sense -- I agree that since the truthiness of `pageData` is being checked, the returned value doesn't necessitate a boolean. Very sleek one-liner to boot 🤠

File: app.js (hunk 5 above)
Comment (alexhoffman-dev) [reply app.js]: Noted -- that makes sense. This a good example of how to make my code flatter which is definitely something I appreciate tips for.

File: app.js [hunk 7]
```diff
@@ -2,23 +2,25 @@ const RickAndMortyAPI = 'https://rickandmortyapi.com/api/character/';
...
 const cardContainer = document.getElementById('card-container');
 const nextPage = document.getElementById('next-page');
 const prevPage = document.getElementById('previous-page');
 searchInput.addEventListener('search', search);
 nextPage.addEventListener('click', page);
 prevPage.addEventListener('click', page);
-
+// prev page starts disabled to prevent decrementing page below 1 
+prevPage.disabled = true; 
 load();
```
Comment (alexhoffman-dev) [inline app.js]: remove this line -- added `disabled` pseudo-class to HTML element

**Comment by Luke9389** [comment]
OK, so to finish this PR off, you need to make the requested changes from those two unresolved topics above.

Then post a comment here saying something like "Updated the code" and re-request a review from me. 

Then I come back, ask for more changes or approve.

Once there's an approval review, the PR gets merged. (`Merge pull request` button down below`)

File: styles.css (hunk 4 above)
Comment (Luke9389) [reply styles.css]: this one isn't resolved yet

File: app.js (hunk 1 above)
Comment (Luke9389) [reply app.js]: > so I've moved it to the end of the function after the forEach loop concludes.

I don't see that here. Have you pushed that change?

File: app.js [hunk 8]
```diff
@@ -2,10 +2,11 @@ const RickAndMortyAPI = 'https://rickandmortyapi.com/api/character/';
 let favoriteCharactersData = [];
 let characterGridData = [];
 let currentPage = 1;
+let currentPageData; 
 
 // ARM BUTTONS
 const searchInput = document.getElementById('filter-search');
-const favoriteBar = document.getElementById('favorite-container');
+const favoriteBar = document.getElementById('favorite-card-container');
```
Comment (alexhoffman-dev) [inline app.js:9]: Created a new container for the favorite cards so that the 'Favorites' header isn't cleared once a favorite card is loaded

File: app.js (hunk 1 above)
Comment (alexhoffman-dev) [reply app.js]: Changes were just pushed -- I made the mistake of never updating my PR after testing in VS Code. I assume that the way to do that is either to make small changes using the VS Code editor tool or to simply stage and push said changes via VS Code?

**Review by Luke9389 — APPROVED** [review]

**Comment by Luke9389** [comment]
Nice! Looks good! Before you merge it, be sure you've tested it all (heh). Don't wanna push any bugs to the live site :-)

**Comment by alexhoffman-dev** [comment]
@Luke9389 I'm going to need to stick to this one for the time being since the Netlify deploy is not happy about an error that my live port via Chrome wasn't concerned about.
